import{CONFIG}from"./config.js";import{load,objects,configuration}from"./sheets.js";
const levelsEl=document.querySelector("#levels"),status=document.querySelector("#status"),seasonEl=document.querySelector("#season");const timers=[];
const yes=v=>/^(true|yes|1|on)$/i.test(String(v??"").trim());const logo=p=>String(p||"").trim().replace(/^\.?\//,"./");
function card(level,s,showName,entry=""){let el=document.createElement(s.Website?"a":"div");el.className=`card ${level.toLowerCase()} ${entry}`;if(s.Website){el.href=s.Website;el.target="_blank";el.rel="noopener noreferrer"}let img=document.createElement("img");img.src=logo(s.Logo);img.alt=s.Name||"Sponsor";el.append(img);if(showName){let n=document.createElement("strong");n.textContent=s.Name;el.append(n)}return el}
function levelView(cfg,list,showName){let sec=document.createElement("section");sec.className=`level ${cfg.level.toLowerCase()}`;let h=document.createElement("h2");h.textContent=`${cfg.level} Sponsors`;sec.append(h);let car=document.createElement("div");car.className="carousel";let prev=document.createElement("button"),next=document.createElement("button"),view=document.createElement("div"),dots=document.createElement("div");prev.textContent="‹";next.textContent="›";prev.ariaLabel=`Previous ${cfg.level} sponsor`;next.ariaLabel=`Next ${cfg.level} sponsor`;prev.className=next.className="arrow";view.className="viewport";dots.className="dots";let i=list.length>1?Math.floor(Math.random()*list.length):0,busy=false;
function dot(){dots.replaceChildren(...list.map((_,x)=>{let d=document.createElement("i");if(x===i)d.className="active";return d}))}
function initial(){view.replaceChildren(card(cfg.level,list[i],showName));dot()}
function move(d){if(busy||list.length<2)return;busy=true;let old=view.querySelector(".card"),ni=(i+d+list.length)%list.length,nw=card(cfg.level,list[ni],showName,d>0?"from-right":"from-left");view.append(nw);requestAnimationFrame(()=>{old.classList.add(d>0?"to-left":"to-right");nw.classList.add("arrive")});setTimeout(()=>{old.remove();nw.classList.remove("from-right","from-left","arrive");i=ni;dot();busy=false},720)}
prev.onclick=()=>move(-1);next.onclick=()=>move(1);car.append(prev,view,next);sec.append(car);if(list.length>1){sec.append(dots);timers.push(setInterval(()=>move(1),Math.max(1,cfg.rotationSeconds)*1000))}else{prev.hidden=next.hidden=true}initial();return sec}
try{let[sr,cr]=await Promise.all([load(CONFIG.sheets.Sponsor),load(CONFIG.sheets.Configuration)]),sponsors=objects(sr),{settings,levels}=configuration(cr),current=settings.CurrentSeason,showName=yes(settings.ShowSponsorName);seasonEl.textContent=current?`Season ${current}`:"";let active=sponsors.filter(s=>s.Season===current&&yes(s.Active));for(let cfg of levels){let list=active.filter(s=>s.Level===cfg.level).sort((a,b)=>(+a.Order||999)-(+b.Order||999));if(list.length)levelsEl.append(levelView(cfg,list,showName))}if(levelsEl.children.length){status.hidden=true;levelsEl.hidden=false}else status.textContent="No active sponsors found for the current season."}catch(e){console.error(e);status.textContent="Unable to load sponsor information."}